services:
  api-server:
    build: .
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 5s
      retries: 5
    networks:
      - test-network

  api-tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    depends_on:
      api-server:
        condition: service_healthy
    volumes:
      - ./tests:/etc/newman
      - ./reports/allure-results:/app/reports/allure-results
    networks:
      - test-network
    entrypoint:
      - sh
      - -c
      - |
        echo '--- [DEBUG] Reporter 확인 ---'
        ls /newman-modules/node_modules | grep allure
        mkdir -p /app/reports/allure-results
        echo '--- Run 1: signup ---'
        newman run /etc/newman/postman_collection.json \
          -e /etc/newman/postman_environment.json \
          -d /etc/newman/data/signup_invalid_data.json \
          -r cli,allure \
          --reporter-allure-export /app/reports/allure-results
        echo '--- Run 2: order_create ---'
        newman run /etc/newman/postman_collection.json \
          -e /etc/newman/postman_environment.json \
          -d /etc/newman/data/order_create_invalid_data.json \
          -r cli,allure \
          --reporter-allure-export /app/reports/allure-results
        echo '--- Run 3: order_update ---'
        newman run /etc/newman/postman_collection.json \
          -e /etc/newman/postman_environment.json \
          -d /etc/newman/data/order_update_invalid_data.json \
          -r cli,allure \
          --reporter-allure-export /app/reports/allure-results
        echo '--- [DEBUG] 파일 확인 ---'
        ls -la /app/reports/allure-results
        sync

networks:
  test-network:
    driver: bridge