name: API Automation CI (Docker Edition)

on:
  push:
    branches: [ "main" ]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create report directory
        run: mkdir -p reports/allure-results

      - name: Configure ephemeral JWT secret
        run: echo "JWT_SECRET=$(openssl rand -hex 32)" >> "$GITHUB_ENV"

      - name: Run Tests with Docker Compose
        run: docker compose up --build --exit-code-from api-tester

      - name: Fix permissions for reports
        if: always()
        run: sudo chmod -R 777 reports

      - name: Debug - List test results
        if: always()
        run: ls -R ./reports

      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline
          allure generate ./reports/allure-results --clean -o allure-report

      - name: Upload Allure Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report